# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AXmYFx15wSAPK7R06vQSsJ1nLDezyJZn
"""

print('Ola Mundo!!!')

"""Exercicio 1"""

x = 6 + 4 * 2
print(x)
x = (4 * 9 + 5)
print(x)
x = (15 + 20 - 30)
print(x)
x = (6 + 5**2)
print(x)

numero_1= 5
numero_1 += 5
print(numero_1)

x = 8
x += 5
x -= 4
x *= 20
x /= 2
print (x)

numero_1 = 2
numero_2 = 4
soma = numero_1 + numero_2
if soma < 10:
  print('A soma é menor que 10')

soma1 = 7 + 8
soma2 = 10 + 5
if soma1 == soma2:
  print('Os resultados são iguais')

x = 8
y = 3
# Analisar a comparação das variáveis
x_result = x < y
print(x_result)
x_result = x == y
print(x_result)
x_result = x >= y
print(x_result)
x_result = x != y
print(x_result)

idade_lucas = 21
idade_carolina = 19
# OPERADOR OR
if(idade_lucas >= 18 or idade_carolina >= 18):
  print('Pelo menos um dos dois é maior de idade')

idade_lucas = 21
idade_carolina = 17
# OPERADOR AND
if(idade_lucas >= 18 and idade_carolina >= 18):
  print('Pelo menos um dos dois é maior de idade')

time_carlos = "Botafogo"
time_luciano = "Flamengo"
time_fabrica = "botafogo"
print(time_carlos is time_fabrica)

x = "botafogo"
y = "flamengo"
z = "botafogo"

xresult = x is z
print(xresult)
xresult = x is not z
print(xresult)
xresult = y is z
print(xresult)
xresult = y is not z
print(xresult)

frutas = {"banana", "laranja", "uva", "ameixa"}

fruta_1 = "ameixa"
fruta_2 = "melancia"

print(fruta_1 in frutas) #True
print(fruta_2 in frutas) #False

x = 4
y = 9
z = 5

xresult = (((2 + 5)*3) + x + 5) < y
print(xresult)
xresult = (((2 + 5)*3) + (x + 5 < y) == (x == 6 + z * 2))
print(xresult)
xresult = (((3 * 6) + x - 3) < z)
print(xresult)
xresult = (((7 * 8) > (x + 4 > y) < (x != 2 + z * 9)))
print(xresult)

nota1 = float(input("Digite a Primeira nota: "))
nota2 = float(input("Digite a Segunda nota: "))

77


if media >= 7:
  print('O Aluno foi aprovado')
7

numero = int(input("Digite um número: "))

if numero >= 30:
  print("o Numero é maior que 30")
else:
  print('O numero é menor que 30')

nota1 = float(input("Digite a Primeira nota: "))
nota2 = float(input("Digite a Segunda nota: "))

#Calcular a média aritmetica
media = (nota1 + nota2) /2

#Verifica se o aluno foi aprovado
if media >= 7:
  print (f"O aluno foi aprovado! Média {media:.2f}")
#Verifica outra condição
elif media >= 5:
  print(f"O aluno está em recuperação! Media {media}")
else:
  print (f"O aluno foi reprovado! Média {media}")

a = int(input("Informe um numero entre 0 e 100: "))
if a > 50:
  print("O número", a,"é maior que 50")
elif a == 50:
  print ("O número informado é igual a 50")
else:
  print ("O número", a, "é menor que 50")

alimento_selecionado = "arroz"

if alimento_selecionado == "arroz":
  print("vamos jantar " + alimento_selecionado)
elif alimento_selecionado == "macarrão":
  print ("vamos jantar " + alimento_selecionado)
else:
  print("o item não consta na lista")